<?php

/**
 * @file
 * Provides a basic payment module implementation for Paymill
 */

define('COMMERCE_PAYMILL_BRIDGE', 'https://bridge.paymill.com/');
define('COMMERCE_PAYMILL_SERVER', 'https://api.paymill.de/v2/');
define('COMMERCE_PAYMILL_MODE_TEST', 'test');
define('COMMERCE_PAYMILL_MODE_LIVE', 'live');

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_paymill_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_paymill'] = array(
    'base' => 'commerce_paymill',
    'title' => t('Paymill'),
    'display_title' => t('Credit card'),
    'description' => t('Provides credit card payment during checkout via Paymill.'),
    'terminal' => FALSE,
  );

  return $payment_methods;
}

/**
 * Implements hook_settings_form().
 */
function commerce_paymill_settings_form($settings = NULL) {
  $form = array();

  $settings = (array) $settings + array(
    'test' => array(
      'private_key' => '',
      'public_key' => '',
    ),
    'live' => array(
      'private_key' => '',
      'public_key' => '',
    ),
    'mode' => COMMERCE_PAYMILL_MODE_TEST,
    'capture_mode' => COMMERCE_CREDIT_AUTH_CAPTURE,
  );

  $form[COMMERCE_PAYMILL_MODE_TEST] = array(
    '#type' => 'fieldset',
    '#title' => t('Test keys'),
    '#collapsed' => FALSE,
  );
  $form[COMMERCE_PAYMILL_MODE_TEST]['private_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Private test key'),
    '#size' => 40,
    '#maxlength' => 32,
    '#default_value' => $settings[COMMERCE_PAYMILL_MODE_TEST]['private_key'],
    '#required' => TRUE,
  );
  $form[COMMERCE_PAYMILL_MODE_TEST]['public_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Public test key'),
    '#size' => 40,
    '#maxlength' => 32,
    '#default_value' => $settings[COMMERCE_PAYMILL_MODE_TEST]['public_key'],
    '#required' => TRUE,
  );

  $form[COMMERCE_PAYMILL_MODE_LIVE] = array(
    '#type' => 'fieldset',
    '#title' => t('Live keys'),
    '#collapsed' => FALSE,
  );
  $form[COMMERCE_PAYMILL_MODE_LIVE]['private_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Private live key'),
    '#size' => 40,
    '#maxlength' => 32,
    '#default_value' => $settings[COMMERCE_PAYMILL_MODE_LIVE]['private_key'],
  );
  $form[COMMERCE_PAYMILL_MODE_LIVE]['public_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Public test key'),
    '#size' => 40,
    '#maxlength' => 32,
    '#default_value' => $settings[COMMERCE_PAYMILL_MODE_LIVE]['public_key'],
  );

  $form['mode'] = array(
    '#type' => 'radios',
    '#title' => t('Transaction mode'),
    '#options' => array(
      COMMERCE_PAYMILL_MODE_TEST => t('Test'),
      COMMERCE_PAYMILL_MODE_LIVE => t('Live'),
    ),
    '#default_value' => $settings['mode'],
  );
  
  $form['capture_mode'] = array(
    '#type' => 'radios',
    '#title' => t('Capture mode'),
    '#options' => array(
      COMMERCE_CREDIT_AUTH_CAPTURE => t('Capture'),
      COMMERCE_CREDIT_AUTH_ONLY => t('Pre-authorize only'),
    ),
    '#default_value' => $settings['capture_mode'],
  );

  return $form;
}

/**
 * Implements hook_menu().
 */
function commerce_paymill_menu() {
  $items = array();

  // Add a menu item for configuring the detail payment rule
  $items['admin/settings/commerce-paymill'] = array(
    'title' => 'Commerce Paymill Configuration',
    'description' => 'Configure the Commerce Paymill module',
    'page callback' => 'commerce_paymill_configure',
    'access arguments' => array('administer payment methods'),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_paymill.admin.inc',
  );

  // Add a menu item for capturing authorizations.
  $items['admin/commerce/orders/%commerce_order/payment/%commerce_payment_transaction/paymill-capture'] = array(
    'title' => 'Capture',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_paymill_capture_form', 3, 5),
    'access arguments' => array('administer payment methods'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 2,
    'file' => 'commerce_paymill.admin.inc',
  );

  return $items;
}

/**
 * Payment method callback: submit form.
 */
function commerce_paymill_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');
  $fields = array(
    'owner' => '',
    'code' => '',
  );
  $default = array();
  $form = commerce_payment_credit_card_form($fields, $default);

  // Render default form - will be inserted again using markup.
  // THIS IS A SECURITY MEASURE TO PREVENT CARD DETAILS BEING TRANSMITTED BACK!
  $markup = drupal_render($form['credit_card']);

  // Create new form with no existing fields.
  $form['credit_card'] = array(
    '#tree' => TRUE,
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'commerce_payment') . '/theme/commerce_payment.theme.css'),
    ),
  );

  // Add fields as markup (with name attributes removed for security).
  $form['credit_card']['fields'] = array(
    '#type' => 'markup',
    '#markup' => $markup,
  );

  // Get order total for order.
  $commerce_order_total = field_get_items('commerce_order', $order, 'commerce_order_total');
  $charge = $commerce_order_total[0];

  // Add hidden fields for amount/currency/Paymill token.
  $form['credit_card']['amount'] = array(
    '#type' => 'hidden',
    '#value' => commerce_currency_amount_to_decimal($charge['amount'], $charge['currency_code']),
  );
  $form['credit_card']['currency'] = array(
    '#type' => 'hidden',
    '#value' => $charge['currency_code'],
  );
  $form['credit_card']['token'] = array(
    '#type' => 'hidden',
    '#required' => TRUE,
  );

  // Load Paymill bridge.
  $key = commerce_paymill_get_key($payment_method['settings'], 'public');
  $settings = array('publicKey' => $key);
  $form['credit_card']['#attached']['js'][COMMERCE_PAYMILL_BRIDGE] = array('type' => 'external');
  $form['credit_card']['#attached']['js'][] = array('data' => array('commercePaymill' => $settings), 'type' => 'setting');
  $form['credit_card']['#attached']['js'][] = drupal_get_path('module', 'commerce_paymill') . '/commerce_paymill.js';
  return $form;
}

/**
 * Payment method callback: submit form validation.
 */
function commerce_paymill_submit_form_validate($payment_method, $pane_form, $pane_values, $order, $form_parents = array()) {
  if (empty($pane_values['credit_card']['token'])) {
    drupal_set_message(t('No Paymill token received. Your card has not been charged. Please enable JavaScript to complete your payment.'), 'error');
    return FALSE;
  }
}

/**
 * Payment method callback: submit form submission.
 */
function commerce_paymill_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  $order->data['commerce_paymill'] = $pane_values;

  // Include Paymill libraries.
  libraries_load('paymill');

  // Get order total for order.
  $commerce_order_total = field_get_items('commerce_order', $order, 'commerce_order_total');

  // Get current API key
  $api_key = commerce_paymill_get_key($payment_method['settings']);

  // Create Commerce transaction.
  $transaction = commerce_payment_transaction_new('commerce_paymill', $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->amount = $charge['amount'];
  $transaction->currency_code = $charge['currency_code'];
  // Set the transaction to failed per default and change that later to success.
  $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
  
  // Get client ID  
  $client_id = commerce_paymill_get_client($order, $payment_method['settings']);
  if (!$client_id) {
    $transaction->message = 'Failed to get client ID from Paymill.';
    commerce_payment_transaction_save($transaction);
    return FALSE;
  }

  // Create payment card
  $payment_params = array(
    'token' => $pane_values['credit_card']['token'],
    'client' => $client_id,
  );
  $payment_service = new Services_Paymill_Payments($api_key, COMMERCE_PAYMILL_SERVER);
  $payment = $payment_service->create($payment_params);
  if (isset($payment['error'])) {
    // The Paymill error structure is completely unknown, so only print it if we
    // get a flat string.
    if (is_scalar($payment['error'])) {
      $error = check_plain($payment['error']);
      drupal_set_message($error, 'error');
    }
    else {
      $error = 'Error when creating payment: ' . check_plain(print_r($payment, TRUE));
      drupal_set_message(t('A payment error occured, please contact the site administrator.'), 'error');
    }
    $transaction->message = $error;
    commerce_payment_transaction_save($transaction);
    return FALSE;
  }

  // Create transaction/preauth
  $transaction_params = array(
    'amount' => $commerce_order_total[0]['amount'],
    'currency' => $commerce_order_total[0]['currency_code'],
    'payment' => $payment['id'],
  );
  if ($payment_method['settings']['capture_mode'] == COMMERCE_CREDIT_AUTH_ONLY) {
    $preauthorization_service = new Services_Paymill_Preauthorizations($api_key, COMMERCE_PAYMILL_SERVER);
    $response = $preauthorization_service->create($transaction_params);
  }
  else {
    $transaction_service = new Services_Paymill_Transactions($api_key, COMMERCE_PAYMILL_SERVER);
    $transaction_params['description'] = 'Order:' . $order->order_id;
    $response = $transaction_service->create($transaction_params);
  }
  
  // Check for errors from the response.
  if (isset($response['error'])) {
    if (is_scalar($response['error'])) {
      $error = check_plain($response['error']);
      drupal_set_message($error, 'error');
    }
    else {
      $error = 'Error when creating transaction: ' . check_plain(print_r($response, TRUE));
      drupal_set_message(t('A transaction error occured, please contact the site administrator.'), 'error');
    }
    $transaction->message = $error;
    commerce_payment_transaction_save($transaction);
    return FALSE;
  }

  // Now handle the successful payment transaction.
  if ($payment_method['settings']['capture_mode'] == COMMERCE_CREDIT_AUTH_ONLY) {
    $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
    $transaction->remote_id = $response['preauthorization']['id'];
  }
  else {
    $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
    $transaction->remote_id = $response['id'];
  }

  // Save transaction.
  commerce_payment_transaction_save($transaction);
}

function commerce_paymill_get_client($order, $settings) {
  global $user;

  // Does the current user already have a client instance?
  if (isset($user->data)) {
    if (isset($user->data['commerce_paymill_client_id'])) {
      return $user->data['commerce_paymill_client_id'];
    }
  }

  // Instantiate client service.
  $api_key = commerce_paymill_get_key($settings);
  $client_service = new Services_Paymill_Clients($api_key, COMMERCE_PAYMILL_SERVER);

  // Create client.
  $client_params = array(
    'email' => $order->mail,
    'description' => 'User:' . $order->uid,
  );  
  $client = $client_service->create($client_params);
  if (isset($client['error'])) {
    drupal_set_message(check_plain($client['error']), 'error');
    return FALSE;
  }

  // Update current user with client ID.
  if ($user->uid > 0) {
    // We should not save global user.
    $user_entity = user_load($user->uid);
    $user_entity->data['commerce_paymill_client_id'] = $client['id'];
    $edit = array('data' => $user_entity->data);
    user_save($user_entity, $edit);
  }

  return $client['id'];
}

/**
 * Get Paymill key from settings.
 */
function commerce_paymill_get_key($settings, $key = 'private') {
  $mode = $settings['mode'];
  $key = $settings[$mode][$key . '_key'];
  return $key;
}

/**
 * Implements hook_libraries_info().
 */
function commerce_paymill_libraries_info() {
  $libraries = array();

  $libraries['paymill'] = array(
    'name' => 'Paymill',
    'vendor' => 'http://www.paymill.com/',
    'download_url' => 'https://github.com/Paymill/Paymill-PHP/archive/master.zip',
    'path' => 'lib/Services/Paymill',
    'version arguments' => array(
      'file' => 'lib/Services/Paymill/Apiclient/Curl.php',
      'pattern' => '@Paymill-php/([0-9\.]+)@',
      'lines' => 40,
    ),
    'files' => array(
      'php' => array(
        'Clients.php',
        'Coupons.php',
        'Exception.php',
        'Offers.php',
        'Payments.php',
        'Preauthorizations.php',
        'Refunds.php',
        'Subscriptions.php',
        'Transactions.php',
      ),
    ),
  );

  return $libraries;
}
