commerce_payment.commerce_payment_gateway.plugin.paymill:
  type: commerce_payment_gateway_configuration
  mapping:
    private_key:
      type: string
      label: 'Private key'
    public_key:
      type: string
      label: 'Public key'
