commerce_payment.commerce_payment_gateway.plugin.paymill:
  type: commerce_payment_gateway_configuration
  mapping:
    test_private_key:
      type: string
      label: 'Private test key'
    test_public_key:
      type: string
      label: 'Public test key'
    live_private_key:
      type: string
      label: 'Live test key'
    live_public_key:
      type: string
      label: 'Live test key'
